// <auto-generated />
namespace MRMS_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class test_tbl_adde : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_tbl_adde));
        
        string IMigrationMetadata.Id
        {
            get { return "202206241820543_test_tbl_adde"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
